"""remove_autoincrement_from_project_id

Revision ID: 6c5e95eb271d
Revises: eb5a93be4784
Create Date: 2026-04-21 17:46:47.281332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5e95eb271d'
down_revision: Union[str, None] = 'eb5a93be4784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
